apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lonn-app-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "lonn.motoren.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lonn-app
            port:
              number: 80
